INSERT INTO Employee(email, firstName, lastName, pwd) VALUES('admin@acture.no', 'Ansatt', 'Admin', 'admin');

INSERT INTO EmployeePFP(image_data, file_type, eId) VALUES('deuef39f4u43843uf48738dh3fbn4yuvbt458th58ngu5ng58ig5', 'images/png', 1);

INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Oliver D', 'oliver.dragland@gmail.com', '"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Mathias O', 'mathias.o@gmail.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Frank Arnesen', 'frank.a@gmail.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Ole Per', 'ole@per.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('XIenfnr', 'freghret@ez.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Tore Bergdal', 'torebergdal@yahoo.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Thomas Skarste', 'thoska.ste@outlook.com', 'ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut', null, 'unhandled');
INSERT INTO ContactMessage(fullname, email, message, messenger, messageStatus) VALUES('Karol Z', 'karol.z@gmail.com', '"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?', null, 'handled');